services:
  application:
    image: controle
    ports:
      - "8080:8080"
    depends_on:
      - database
  database:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: controleGastos