spring:
  datasource:
    url: jdbc:postgresql://database:5432/controleGastos
    password: 123456
    username: postgres
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true